version: '3.9'

services:

  ml-service:
    build: ./ml-model
    image: greed707/medical-ml:latest
    ports:
      - "8000:8000"

  backend:
    build: ./backend
    image: greed707/medical-backend:latest
    ports:
      - "8081:8081"
    depends_on:
      - ml-service

  frontend:
    build: ./frontend
    image: greed707/medical-frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
